### ISSUE TITLE
楷書字形投稿（基於文鼎PL楷體修改）

### ISSUE THREAD

**Issue by bingzhi2021** [ichitenfont/FuturePlans#3]
如果各位前輩覺得滿意，希望能接手並發佈這款字型！

[I.KhraiThex.zip](https://github.com/ichitenfont/FuturePlans/files/6795326/I.KhraiThex.zip)
[ARPHICPL.TXT](https://github.com/ichitenfont/FuturePlans/files/6793496/ARPHICPL.TXT)
[「通體」研訂原則.txt](https://github.com/ichitenfont/FuturePlans/files/6793495/default.txt)
[習慣差異.pdf](https://github.com/ichitenfont/FuturePlans/files/6795327/default.pdf)

**Comment by i-font** [comment]
感謝閣下投稿。唯目前人手和時間非常緊張，不論一點明體，還是我們工作小組數年前已定下的修改思源黑體計劃，都只能匍匐行進，恐怕我們需要至少數年時間才有機會騰出人手處理這意料之外的新計劃，敬望見諒！

此外，速讀過閣下的準繩，似乎頗多與「傳承字形標準化文件」之規定相異者，甚至整套規定，似乎頗有以我們所不處理的臺標改訂而成的味道。讀閣下之說明，大概是閣下以碑帖取樣的結果。唯「傳承字形標準化文件」及相關計劃，乃在符合約定俗成中盡力取字理最優者，而碑帖並非今天漢字約定俗成字形的唯一來源。如「半部件」，閣下取「丷」形，大抵認爲從碑帖之眾。然而這字字義與「八」關係極大，取「八」形，則字理明顯較優，而仍不悖約定俗成。至於「夂」居下穿頭，更似乎是臺標特立獨行而閣下沿襲之，碑帖裏也不是常態。

凡此種種，也許我們眞的接手時，還要再斟酌，也許修訂準繩，也許另擬名號，屆時望閣下海涵！

**Comment by bingzhi2021** [comment]
感謝回覆。楷書字體，向來以書寫習慣為重，自雕版印刷誕生千餘年來，完全依照字理刻寫者，恐僅有《開成石經》、《宋本廣韻》、《乾隆石經》等寥寥數本耳。且自明中葉膚廓字誕生以降，凡追求字理者，無不棄用軟字而改採硬體，以求點畫詳盡。貴坊所定點校表，既已包容理據略遜，而有益美觀之印刷筆形（如「艹」、「兹」、「益」、「常」等），倘得准此釐定楷書標準，整理常見之正通筆形、訛混異體，尊重其固有習慣，竊以為並無不妥（余工小楷數年，可自書其字樣）。「夊」居下穿頭係楷書常見寫法，亦為《康熙》、《大漢和》所採正形，在214部首中獨立於「夂」，非臺標所獨也。

**Comment by i-font** [comment]
非，「夊」穿頭者，不論在《康熙》、《大漢和》，或在書帖，亦僅少數。

至於楷書者，卻眞的有更注重字理字源、更接近「一點明體」的準繩，如《十三經集字摹本》，不獨《宋本廣韻》和石經等。若冠「一點」之名，卻捨近就遠，大量不劃一，恐非良法。

我不是盲目要求「一點」的楷體與「一點明體」高度一致，明楷、本質有異，自可斟酌取捨。但若高度不一致，也必令人困惑。況且本計劃本身是保留及傳揚不悖於約定俗成且字理佔優的字形，以免只有「臺標」一鎚定音，糾正世人以爲「正體/正字=臺標」的錯誤觀念。若最終結果僅爲臺標的修訂版本，恐怕最少宜另行立項、另冠名號爲尚。

**Comment by SyaoranHinata** [comment]
秉之兄也不必急於關帖，這話題也只是初步探討，尚有許多可思考之空間。
如果說另立名號，不知秉之兄有沒看法？比如「一線」楷體、「一葉」楷體、「二點」楷體等，閣下覺得如何？

**Comment by bingzhi2021** [comment]
@SyaoranHinata
已作為「高書楷體」發佈。
https://github.com/bingzhi2021/KauSjo_KhraixThex
