### ISSUE TITLE
关于：一點源黑 的疑问

### ISSUE THREAD

**Issue by TakWolf** [ichitenfont/FuturePlans#4]
您好，我在脸书社团中看到有这个消息：

https://www.facebook.com/groups/inheritedglyph/permalink/6094939563881931

> 思源黑體已經在2021年4月28日更新可變字體版，而一點團隊接收到協助處理的資源，因此一點團隊在此正式重啟【一點源黑】計劃，並且開始招募協作人員一同檢查修改思源黑體至傳承字型。

但是我没有找到后续的消息。

想问一下，这个专案已经确定要进行了吗？
如果是，在哪里可以关注到开发进度或者消息呢。

**Comment by i-font** [comment]
感謝査詢！由於工程浩大，我們目前仍在製作中，且仍缺乏人手。如果閣下願意幫忙，我們非常歡迎！

**Comment by ghost** [comment]
Hello,
I'm Kaede. I am a Japanese speaker living in Japan.

I have great interest in and sympathy for this project. Is there anything I can do to help?

I don't understand Vernacular Chinese or English, so I use machine translation.
I am learning Literary Chinese.
