### ISSUE TITLE
關於該計畫的英文名「ichitenfont」

### ISSUE THREAD

**Issue by ShikiSuen** [ichitenfont/FuturePlans#5]
內木一郎這個名字也好，Syaoran 這個取自「[Tsubasa Chronicles](https://zh.wikipedia.org/wiki/TSUBASA%E7%BF%BC%E8%A7%92%E8%89%B2%E5%88%97%E8%A1%A8#%E5%B0%8F%E7%8B%BC)」的男主角的名字也好，都是有意要取日文名。
但偏偏「一點明體」這個名字起成「ichiten」就真的不倫不類。
正確的讀法的羅馬拼寫是「itten」，對應假名是「いってん」。
於是這個組織名稱可以考慮更名為「ittenfont」了。

**Comment by ghost** [comment]
固有名詞ですし、いちてんと読ませてもいいのでは？

**Comment by ghost** [comment]
I'm not familiar with the Tsubasa Chronicles, but I think either "Ichiten" or "Itten" is fine as a Japanese reading.

**Comment by ShikiSuen** [comment]
@chankaede Syaoran 就是小狼，是 Tsubasa Chronicles 的男主角、也是女主 Sakura 的交往對象。

**Comment by ShikiSuen** [comment]
@i-font 這個帳號背後的控制人是誰？是內木一郎還是另有其人？
